site_name: Introduction to RNA-Seq - From quality control to pathway analysis

nav:
    - Home: index.md
    - Precourse preparations: 
        - prerequisites: precourse.md
        - UNIX crash course: days/unix_crash.md
        - R crash course: days/R_crash.md
    - Course schedule: course_schedule.md
    - Slides notes (draft): slides_notes.md
    - Cheatsheets: cheatsheets.md
    - Day1 :
        - RNAseq - technologies and design : days/design.md
        - Server login + unix fresh up : days/server_login.md
        - Quality control : days/quality_control.md
        - Sequence trimming : days/trimming.md

    - Day2 :
        - Reads mapping : days/mapping.md
        - Differential Expression Inference : days/DE.md
        - Enrichment analysis : days/enrichment.md



# Repository
repo_name: sib-swiss/RNAseq-introduction-training
repo_url: https://github.com/sib-swiss/RNAseq-introduction-training
site_url: 

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
